export const NICHOS = [
  { value: "administrativo", label: "Administrativo" },
  { value: "aduaneiro", label: "Aduaneiro" },
  { value: "agronegocio", label: "Agronegócio" },
  { value: "ambiental", label: "Ambiental" },
  { value: "bancario", label: "Bancário" },
  { value: "civel", label: "Cível" },
  { value: "compliance", label: "Compliance" },
  { value: "consumidor", label: "Consumidor" },
  { value: "cooperativo", label: "Cooperativo" },
  { value: "desportivo", label: "Desportivo" },
  { value: "digital", label: "Digital / Crimes Cibernéticos" },
  { value: "educacional", label: "Educacional" },
  { value: "eleitoral", label: "Eleitoral" },
  { value: "empresarial", label: "Empresarial" },
  { value: "entretenimento", label: "Entretenimento / Fashion Law" },
  { value: "familia", label: "Família" },
  { value: "imobiliario", label: "Imobiliário" },
  { value: "intelectual", label: "Propriedade Intelectual" },
  { value: "internacional", label: "Internacional" },
  { value: "lgpd", label: "LGPD e Proteção de Dados" },
  { value: "militar", label: "Militar" },
  { value: "minerario", label: "Minerário" },
  { value: "penal", label: "Penal / Criminal" },
  { value: "previdenciario", label: "Previdenciário" },
  { value: "recuperacao_judicial", label: "Recuperação Judicial e Falência" },
  { value: "saude", label: "Saúde / Médico" },
  { value: "sistemico", label: "Sistêmico" },
  { value: "sucessoes", label: "Sucessões (Inventários)" },
  { value: "terceiro_setor", label: "Terceiro Setor (ONGs)" },
  { value: "trabalhista", label: "Trabalhista" },
  { value: "transito", label: "Trânsito" },
  { value: "tributario", label: "Tributário" },
  { value: "urbanistico", label: "Urbanístico" },
  { value: "outros", label: "Outros" }
];
